name: Release

on:
  push:
    branches:
      - main
      - feat/workflow # TEST
    tags:
      - v*

concurrency: releaser

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo 'flags=--snapshot' >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
